### ISSUE TITLE
Exporting all sprites corrupts the file

### ISSUE THREAD

**Issue by SapitoSucio** [Tokeiburu/ActEditor#1]
Try this scenario:

Open poring.act
Click on "File", then "Export All Sprites"
Choose to export all sprites as png somewhere (This operation converts all the residing sprites to BGRA)
Ctrl + S
Close the file and open it again
Gets Corrupted

**Comment by Tokeiburu** [comment]
The exported images are modifying the images from the sprite file itself without caring about the act structure at all. That will be fixed in 1.2.7.
