### ISSUE TITLE
Some sprites are getting deleted after saving 

### ISSUE THREAD

**Issue by SapitoSucio** [Tokeiburu/ActEditor#2]
When converting all sprites to BGRA, there is an error which affects "apparently" small images.

The images at the end could be removed if these are small.

Take for example zombie.act, convert all sprites to BGRA, Save and reopen the file, it will be missing the last 2 images of the zombie's flies.

I think it's not removed because, even tho the sprites are missing, the sprites ID are still there, I couldn't fix it with ActEditor
![image](https://github.com/Tokeiburu/ActEditor/assets/7357354/7da80dae-5ce7-4bba-9cd3-2bbf34c82442)

I found out you can re-add the missing files using GrfEditor and then placing a big image at the end so It won't get deleted again

Some Mobs affected:

Eggyra
zombie_master
zombie_h
ghoul
wilow
venomous
toxious_z
sailor_skeleton

and many others

**Comment by Tokeiburu** [comment]
You're right; if there is no palette in the Sprite file it won't attempt to load images if the reader is past the last 1024 bytes. Fixed in version 1.2.7.
